apiVersion: v2
name: galleon-shell
description: Galleon K8s-native CSS Grid shell — UI + backend
type: application
version: 0.1.0
appVersion: "main.20260331.1922"

dependencies:
  - name: galleon-backend
    version: "0.1.0"
    repository: "file://../galleon-backend"
