{{- if .Values.polyfea.webcomponent.enabled }}
{{- with .Values.polyfea.webcomponent }}
apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: {{ .name | default (include "galleon-shell.fullname" $) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "galleon-shell.labels" $ | nindent 4 }}
spec:
  microFrontend:
    name: {{ $.Values.polyfea.microfrontend.name | default (include "galleon-shell.fullname" $) }}
  element: {{ .element }}
  {{- with .attributes }}
  attributes:
    {{- range . }}
    - name: {{ .name }}
      {{- if and (eq .name "mf-name") (not .value) }}
      value: {{ $.Values.polyfea.microfrontend.name | default (include "galleon-shell.fullname" $) | quote }}
      {{- else if and (eq .name "mf-namespace") (not .value) }}
      value: {{ $.Release.Namespace | quote }}
      {{- else }}
      value: {{ .value | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- with .displayRules }}
  displayRules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
