{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ include "galleon-backend.k8sNamespace" . }}
  labels:
    {{- include "galleon-backend.labels" . | nindent 4 }}
type: Opaque
data:
  password-hash: {{ .Values.auth.passwordHashBase64 | quote }}
  jwt-secret: {{ .Values.auth.jwtSecretBase64 | quote }}
{{- end }}
